image: alpine:3.20

stages:
  - sync

github_sync:
  stage: sync
  only:
    - tags
  tags:
    - k8s-runner
  script:
    - sed -i 's/https:\/\/dl-cdn.alpinelinux.org/http:\/\/mirrors.homelab.mathcrowd.cn/' /etc/apk/repositories
    - apk add --no-cache -f openssh git
    - export GIT_TRACE=1 GIT_CURL_VERBOSE=1
    - sh ./scripts/github_sync.sh
